# Generated by Django 3.1.5 on 2021-01-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=100, verbose_name="Street' name")),
                ('block', models.PositiveSmallIntegerField(verbose_name="Block's name")),
                ('house', models.PositiveSmallIntegerField(verbose_name='Number of house')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="City's name")),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Autor's name")),
                ('age', models.PositiveSmallIntegerField(max_length=4, verbose_name="Autor's age")),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Autor's name")),
                ('age', models.PositiveSmallIntegerField(max_length=4, verbose_name="Autor's age")),
            ],
        ),
        migrations.CreateModel(
            name='Autors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Autor's name")),
                ('age', models.PositiveSmallIntegerField(max_length=4, verbose_name="Autor's age")),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.addresses', verbose_name="Autor's address")),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.cities', verbose_name='City'),
        ),
    ]
