# Generated by Django 3.1.5 on 2021-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name="Book's image"),
        ),
        migrations.AlterField(
            model_name='bookslist',
            name='rating',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=15, null=True, verbose_name="Book's rating"),
        ),
    ]
