# Generated by Django 3.1.5 on 2021-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autors',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name="Autor's age"),
        ),
    ]
