# Generated by Django 3.1.5 on 2021-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210131_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name="Autor's age"),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name="Autor's age"),
        ),
    ]
