# Generated by Django 3.1.5 on 2021-01-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210131_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresses',
        ),
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='autors',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autors'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
