# Generated by Django 3.1.5 on 2021-01-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('books', '0006_auto_20210131_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishers',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='books.addresses', verbose_name="Autor's address"),
        ),
    ]
