# Generated by Django 3.1.5 on 2021-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_publishers_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autors',
            name='age',
        ),
        migrations.RemoveField(
            model_name='autors',
            name='name',
        ),
        migrations.AddField(
            model_name='autors',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name="Autor's date of birth"),
        ),
        migrations.AddField(
            model_name='autors',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='autors',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name'),
        ),
    ]
