# Generated by Django 3.1.5 on 2021-01-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210131_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autors',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.addresses', verbose_name="Autor's address"),
        ),
    ]
