# Generated by Django 3.1.5 on 2021-01-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('books', '0009_auto_20210131_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='autors',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.addresses', verbose_name="Autor's address"),
        ),
        migrations.AlterField(
            model_name='autors',
            name='date_of_birth',
            field=models.DateField(verbose_name="Autor's date of birth"),
        ),
        migrations.AlterField(
            model_name='autors',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.addresses', verbose_name="Autor's address"),
        ),
    ]
