# Generated by Django 3.1.5 on 2021-02-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210131_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name="City's descriprion"),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='books.cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='autors',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autors', to='books.addresses', verbose_name="Autor's address"),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='books.addresses', verbose_name="Publisher's address"),
        ),
    ]
