# Generated by Django 3.1.5 on 2021-03-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.TextField(verbose_name='Phone')),
                ('status', models.CharField(choices=[('0', 'Awaiting payment'), ('1', 'Accepted for execution'), ('2', 'Submitted')], max_length=30, verbose_name='Status')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Date of create')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
