# Generated by Django 3.1.5 on 2021-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Status'),
        ),
    ]
