# Generated by Django 3.1.5 on 2021-03-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210321_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Canceled', 'Canceled'), ('Finished', 'Finished')], max_length=30, verbose_name='Status'),
        ),
    ]
