# Generated by Django 3.1.5 on 2021-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210322_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(null=True, verbose_name='Phone'),
        ),
    ]
