# Generated by Django 3.1.5 on 2021-03-12 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20210312_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Date of create')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('date_of_create', models.DateField(auto_now_add=True, verbose_name='Date of create')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Date of update')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.bookslist', verbose_name='Book in a cart')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
